/* Curated from the cited pages in this repository. Keep the claim and its caveat together. */
const ROOT = "../";
const BRANCHES = {
  disque: { label: "Disqué & Schaaf", color: "#7b5b9a" },
  blevins: { label: "Blevins leads", color: "#a96355" },
  kramer: { label: "Kramer & Bosch", color: "#276d7b" },
  miller: { label: "Miller & Raber", color: "#a27432" },
  weatherford: { label: "Weatherford", color: "#486c9a" },
  smith: { label: "Smith & Blevins", color: "#6d8292" },
  cordaro: { label: "Cordaro & Caucci", color: "#936d48" },
  monty: { label: "Monty", color: "#61824f" },
  context: { label: "Shared context", color: "#717878" }
};
const TYPES = ["Birth", "Marriage", "Work", "Migration", "Military", "Home", "Travel", "Death", "History", "Research"];
const item = (id, year, date, title, branch, type, evidence, summary, detail, caveat, place, people, sources, story) => ({ id, year, date, title, branch, type, evidence, summary, detail, caveat, place, people, sources, story });
const EVENTS = [
  item("bernhard-mill",1684,"1684","Bernhard Disqué offers to rebuild a mill","disque","Work","recorded","A Palatinate mill story begins in Siebeldingen.","A specialist mill history quotes Bernhard Disqué's offer to rebuild a ruined mill. It shows enterprise and access to a working site, though the surviving account gives no defensible income or net-worth figure.","The later chain from this family to Justin's Magdalena Disque remains a research question.","Siebeldingen, Palatinate",["Bernhard Disqué"],[["Mill-family history","https://www.eberhard-ref.net/pf%C3%A4lzisches-m%C3%BChlenlexikon/pf%C3%A4lzische-m%C3%BCllerfamilien/litera-d/"]],"branches/disque-schaaf.md"),
  item("sebastian-birth",1696,"1696, chart date","Sebastian Johann Disqué is born","disque","Birth","proposed","The family chart places Sebastian in Siebeldingen.","The inherited chart gives 12 November 1696. A specialist mill history documents Sebastian's later work and marriage, but this exact birth date still needs a church entry.","Treat the date as a search target, not a verified vital record.","Siebeldingen, Palatinate",["Sebastian Johann Disqué"],[["Chart transcription",ROOT+"research/chart-transcription.md"]],"branches/disque-schaaf.md"),
  item("disque-marriage",1718,"1718","Sebastian Disqué marries Anna Barbara Schaaf","disque","Marriage","recorded","A mill-working Palatinate family takes shape.","The specialist mill history reports their marriage and describes leasehold mills associated with Sebastian and different sons. These were productive assets, but there is no proof every descendant inherited a share.","The lineage from them to the later Pennsylvania Magdalena remains under review.","Palatinate, Germany",["Sebastian Disqué","Anna Barbara Schaaf"],[["Mill-family history","https://www.eberhard-ref.net/pf%C3%A4lzisches-m%C3%BChlenlexikon/pf%C3%A4lzische-m%C3%BCllerfamilien/litera-d/"]],"branches/disque-schaaf.md"),
  item("goochland-grants",1737,"15 Aug 1737","James Blevin receives two Goochland grants","blevins","Home","recorded","Patents describe 400 and 295 acres on Little Muddy Creek.","The Library of Virginia indexes two grants to James Blevin. Later deeds confirm transactions involving both tracts and call the seller James Blevin/Bleavin.","This James is not proved to be the later Smith River hunter, Revolutionary pensioner, or Ashley's ancestor.","Goochland County, Virginia",["James Blevin, Goochland landholder"],[["400-acre patent","https://lva.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma990007249560205756&context=L&vid=01LVA_INST:01LVA&lang=en"],["295-acre patent","https://lva.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma990007249570205756&context=L&vid=01LVA_INST:01LVA&lang=en"]],"branches/blevins-colonial-james.md"),
  item("goochland-deeds",1743,"1743–1745","James sells the Little Muddy Creek tracts","blevins","Home","recorded","Three deeds trace two sales and a correction.","Original Goochland deeds show a 295-acre sale in 1743, a 400-acre sale in 1744, and a corrective deed in 1745. The last calls the seller James Bleavin Senior of Brunswick County.","‘Senior’ distinguishes a namesake but by itself does not prove a father–son relationship.","Goochland and Brunswick counties, Virginia",["James Bleavin Senior"],[["Original deed links and reading",ROOT+"branches/blevins-colonial-james.md#the-goochland-landholder-in-his-own-records"]],"branches/blevins-colonial-james.md"),
  item("pensioner-birth",1762,"c. 1761–1762","A different James Blevins recalls his birth","blevins","Birth","proposed","The future pensioner said he was born somewhere in New England.","In 1832 James recalled a lost family-Bible date of 25 December 1762, but his stated age implies 1761. He said his family moved to Virginia while he was an infant.","His father is unnamed. He cannot be the adult Goochland grantee of 1737; his connection to Ashley is unknown.","New England, exact town unknown",["James Blevins, Revolutionary pensioner"],[["Pension S32121 transcription","https://revwarapps.org/s32121.pdf"]],"branches/blevins-revolutionary-james.md"),
  item("peach-bottom",1772,"1772–1801","A James Blevins occupies Peach Bottom land","blevins","Home","proposed","A later lawsuit abstract links a James and son John.","An abstract of an 1805 land case says James held a Peach Bottom tract from 1772 until his death in 1801 and identifies John Blevins as a son. The original case file still needs reading.","Do not merge this James with either the Goochland landholder or the younger pensioner by name alone.","Peach Bottom, Virginia",["James Blevins, Peach Bottom","John Blevins"],[["Lawsuit abstract","https://yanceyfamilygenealogy.org/KenShirleyGenealogyBooks/blevins.pdf#page=168"]],"branches/blevins-colonial-james.md"),
  item("kings-mountain",1780,"7 Oct 1780","King’s Mountain changes the southern war","blevins","Military","proposed","James later claimed he fought with William Campbell’s Virginians.","Patriot militia surrounded Ferguson's Loyalists on a wooded South Carolina ridge. The roughly hour-long battle ended with Ferguson killed and his force defeated, disrupting Cornwallis's advance. James's 1832 pension testimony says he fought there; fellow volunteer John Stone confirmed James departed toward the battle but did not see him fight.","James's battlefield presence is a pension claim with partial corroboration. His descent link to Ashley remains unknown.","King’s Mountain, South Carolina",["James Blevins, pensioner","William Campbell","Patrick Ferguson"],[["James's pension testimony","https://revwarapps.org/s32121.pdf"],["National Park Service battle history","https://www.nps.gov/blri/learn/historyculture/overmountain-men.htm"]],"branches/blevins-revolutionary-james.md#what-happened-at-kings-mountain"),
  item("james-pension",1832,"12 Nov 1832","James gives his own migration and war account","blevins","Research","recorded","A sworn pension declaration preserves childhood moves and service claims.","In Lawrence County, Indiana, James described a New England birth, childhood in Virginia, southern campaigning, a later move near Knoxville and settlement in Indiana around 1821. A pension notation awards $20 annually for six months of Virginia militia service.","The pension file is evidence that he made these statements; its original images and his parentage remain to be checked.","Lawrence County, Indiana",["James Blevins, pensioner"],[["Pension S32121 transcription","https://revwarapps.org/s32121.pdf"]],"branches/blevins-revolutionary-james.md"),
  item("matthew-birth",1840,"29 Aug 1840, chart date","Matthew Kramer is placed in the family chart","kramer","Birth","proposed","A proposed early ancestor of the Wilkes-Barre Kramers.","The inherited chart gives this date and later a Wilkes-Barre marriage to Magdalena Disque. Direct birth and marriage records are needed to join him securely to the directory-listed Matthias Kramer.","Matthew and Matthias may be the same man, but the identification is not proved.","Place not established",["Matthew / Matthias Kramer"],[["Chart transcription",ROOT+"research/chart-transcription.md"]],"branches/kramer.md"),
  item("knittelsheim-estate-1847",1847,"29 Sep 1847, advertised","An indivisible Disqué mill estate faces auction","disque","Work","proposed","A notice lists grain, oil and gypsum machinery, plus a hemp machine.","After miller Johann Sigmund Disqué died, a Knittelsheim auction notice described the mill, residence and farm buildings as an indivisible estate. A historian reports that the advertised auction apparently did not complete, leaving heirs with interests afterward.","The original notice, deed, final outcome and price have not been inspected. This miller is not yet linked through records to Justin's Pennsylvania Magdalena Disque.","Knittelsheim, Palatinate",["Johann Sigmund Disqué","Amalia Margaretha Disqué","Barbara Mathilde Disqué"],[["Mill history quoting auction notice","https://www.eberhard-ref.net/pf%C3%A4lzisches-m%C3%BChlenlexikon/pf%C3%A4lzische-m%C3%BChlen-u-m%C3%BChlorte/kleinottweiler-kusel/"],["Asset ledger",ROOT+"research/assets-by-generation.md"]],"branches/disque-schaaf.md"),
  item("samuel-weatherford-1850",1850,"1850","Samuel and Jane's Virginia-born household","weatherford","Home","recorded","An earlier Weatherford household appears in Halifax County.","The census places Samuel, Jane and 17-year-old Thomas together in Banister district and calls all three Virginia-born. A 1855 marriage of Thomas E and Julia Oakes names Samuel and Jane as his parents; later records call George's father Asa T.","The Thomas E / Asa T identification is probable but unresolved. Samuel and Jane's parents and an immigrant are unknown.","Halifax County, Virginia",["Samuel Wetherford","Jane Wetherford","Thomas / Asa Thomas Weatherford, proposed"],[["1850 census","https://www.familysearch.org/ark:/61903/1:1:M8D3-227?lang=en"],["1855 marriage","https://familysearch.org/ark:/61903/1:1:68TT-61CV?lang=en"]],"branches/weatherford-early-virginia.md"),
  item("weatherford-oakes-1855",1855,"19 Dec 1855, indexed","Thomas E. Weatherford and Julia Oakes marry","weatherford","Marriage","recorded","The full Halifax County register places their entry among their neighbors' marriages.","The indexed marriage names Thomas E. Weatherford, Julia Oakes, and Thomas's parents Samuel and Jane. The original two-page spread is saved so the entry can be checked against its column headings and neighboring rows.","Later records call George Weatherford's father Asa T.; Thomas E. and Asa T. may be the same man, but that identification is not settled.","Halifax County, Virginia",["Thomas E. Weatherford","Julia Oakes","Samuel Weatherford","Jane Weatherford"],[["Saved register spread",ROOT+"sources/records/halifax-weatherford-oakes-marriage-register-1855.jpg"],["FamilySearch original","https://www.familysearch.org/ark:/61903/3:1:3QS7-L9XF-29M3-F?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3A68TT-61CV&action=view&lang=en&groupId=M98Y-PF6"]],"branches/weatherford-early-virginia.md"),
  item("marshall-service",1862,"1862–1863","Marshall Miller serves with Pennsylvania militia","miller","Military","recorded","An 1890 veterans schedule names his unit.","The original veterans schedule lists Marshall Miller with Company K, 171st Pennsylvania Infantry and mentions fever and a regimental hospital. The household match to Gad Marshall Miller is strong.","The schedule does not place him in a named battle; a service or pension file is the next check.","Columbia County, Pennsylvania",["Gad Marshall Miller"],[["Original veterans schedule","https://www.familysearch.org/ark:/61903/3:1:939V-R9SW-RK?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AK89T-N4L&action=view&cc=1877095&lang=en"]],"context/civil-war-family-lines.md"),
  item("disque-migration",1864,"1864","Magdalena Fröhlich’s documented family travels to America","disque","Migration","recorded","A widow and four named children left during a Palatinate migration peak.","An institutional card reports Magdalena Fröhlich's 1864 move with four children after her husband's 1853 death. Regional historians describe an 1864–1873 departure peak linked to divided farmland, crowded trades and earlier economic crises. These conditions may help explain the setting, but her own motive is not recorded.","The chart's Magdalena Disque, later said to marry Matthew Kramer, is absent from that child list. Her participation is unproved; the indexed route and original passenger list need comparison.","Palatinate → United States",["Magdalena Fröhlich Disqué"],[["Palatinate migration card","https://migration.pfalzgeschichte.de/person/98001"],["Regional historical exhibition","https://www.auswanderung-rlp.de/ziele-der-auswanderung/auswanderung-nach-nordamerika/ausstellung-zur-auswanderung-2010.html"]],"branches/disque-schaaf.md"),
  item("matthew-marriage",1866,"26 Aug 1866, chart date","Matthew Kramer and Magdalena Disque reportedly marry","kramer","Marriage","proposed","The family chart places this marriage in Wilkes-Barre.","The date and couple appear in the inherited chart. A church or civil record would establish the marriage and help separate Matthew, Matthias, and the documented 1864 migrant household.","Do not assume Magdalena was one of the four children on the 1864 migration card.","Wilkes-Barre, Pennsylvania",["Matthew Kramer","Magdalena Disque"],[["Chart transcription",ROOT+"research/chart-transcription.md"]],"branches/kramer.md"),
  item("cordaro-birth",1878,"13 Jan 1878, passport reading","An Italian passport points to Sutera","cordaro","Birth","proposed","The bearer appears to be Onofrio Cordaro, a farm worker.","A family-held passport names Sutera, Caltanissetta and appears to give this birth date, a father Giuseppe and mother Maria. The photographed pages do not show when or whether he crossed the Atlantic.","A same-name child born in 1898 died in 1899 and is not this adult bearer. The 1878 birth, U.S. voyage and connection to Patricia Cordaro Kramer remain unproved.","Sutera, Sicily",["Onofrio Cordaro, provisional reading"],[["Family passport photograph",ROOT+"sources/family/italian-passport-details.jpg"],["1899 death index","https://www.familysearch.org/ark:/61903/1:1:Q2HC-JQBM?lang=en"]],"branches/cordaro-passport-lead.md"),
  item("cordaro-italy-marriage",1899,"1 Aug 1899","Antonio Cordaro and Pietra Magro marry in Sicily","cordaro","Marriage","recorded","Their Italian civil index names both spouses and their home towns.","Antonio, 21, was reported born in Sutera; Pietra, 20, in Milocca. They married at Milocca. Antonio's parents were Giuseppe and Maria Tona. A later Pennsylvania application names Anthony and Petra as Joseph Cordaro's parents.","The original Italian act and passenger records should be checked; a tree-attached birth index conflicts on Antonio's birthplace.","Milocca, Caltanissetta, Sicily",["Antonio Cordaro","Pietra Magro"],[["Italian marriage index","https://www.familysearch.org/ark:/61903/1:1:6NCZ-7RPP?lang=en"],["1938 application",ROOT+"sources/records/cordaro-caucci-marriage-1938.jpg"]],"branches/cordaro-passport-lead.md"),
  item("ada-corderman-1900",1900,"4 Jun 1900 census","Ada Corderman lives with Wilson grandparents","miller","Home","recorded","Ada A., her siblings and widowed mother live with John and Sarah Wilson.","The original census places Ada A. Corderman, siblings Ella and Emery, and widowed mother Rosa E. in John and Sarah Wilson's Davidson Township household. A later census places a same-age Elmeda with William Reese nearby.","The 1900 page gives Ada an October 1890 birth, conflicting with Paulene's 1888 and a memorial's 1891. Her match to Elmeda Reese is strong but circumstantial.","Davidson Township, Sullivan County, Pennsylvania",["Ada A. Corderman","Rosa E. Corderman","John Wilson","Sarah Wilson"],[["Saved original census",ROOT+"sources/records/ada-corderman-wilson-household-1900.jpg"],["MyHeritage record","https://www.myheritage.com/research/record-10131-49221936/ada-a-corderman-in-1900-united-states-federal-census"]],"branches/miller-gower-reese.md#ada-and-william-19001918"),
  item("reese-household-1910",1910,"10 May 1910 census","William and Elmeda Reese raise Ruth","miller","Home","recorded","The original census places the young Reese family in Davidson Township.","William Reese, 26, wife Elmeda, 20, and daughter Ruth, 1, share a Davidson Township household. The name, age and place suggest Elmeda was Ada A. Corderman from the 1900 Wilson household.","The 1910 schedule does not give Elmeda's maiden surname; the identity match still needs a marriage or vital record.","Davidson Township, Sullivan County, Pennsylvania",["William Reese","Elmeda Reese","Ruth Reese"],[["Saved original census",ROOT+"sources/records/elmeda-william-reese-household-1910.jpg"],["FamilySearch indexed record","https://www.familysearch.org/ark:/61903/1:1:MG7J-QL3?lang=en"]],"branches/miller-gower-reese.md#ada-and-william-19001918"),
  item("william-reese-draft-1918",1918,"12 Sep 1918","William Reese names Meda as nearest relative","miller","Work","recorded","His signed card records woods labor near Eagles Mere and a Muncy Valley home.","William Harrison Reese reported a 12 March 1884 birth, rural route 2 Muncy Valley residence, woods labor for Joseph Nolan near Eagles Mere, Meda Reese as nearest relative, and blindness in his right eye.","A draft card is not proof of service. FamilySearch's index appears to mistake his March birth day for the September registration date.","Muncy Valley and Eagles Mere, Pennsylvania",["William Harrison Reese","Meda Reese"],[["Saved original draft card",ROOT+"sources/records/william-harrison-reese-draft-card-1918.jpg"],["FamilySearch record","https://www.familysearch.org/ark:/61903/1:1:4D7K-94N2?lang=en"]],"branches/miller-gower-reese.md#ada-and-william-19001918"),
  item("cordaro-arrival-window",1910,"By 1910, inferred","The Cordaro family settles in Pennsylvania","cordaro","Migration","recorded","Italy-born parents and a Pennsylvania-born son appear together in 1920.","The census records Anthony/Antonio and Petria/Pietra born in Italy, daughters Fannie and Mary born there, and son Joseph, about 10, born in Pennsylvania. Anthony reported arrival in 1895 and Petria in 1909.","These are reported census years, not confirmed ship arrivals. Anthony may have made more than one crossing; no voyage has been identified.","Italy → West Wyoming, Pennsylvania",["Antonio Cordaro","Pietra Magro","Joseph Cordaro"],[["1920 census","https://www.familysearch.org/ark:/61903/1:1:M611-V9M?lang=en"]],"branches/cordaro-passport-lead.md"),
  item("ferdinand-older-birth",1882,"c. 1882","Ferdinand Kramer, the older foreman, is born","kramer","Birth","recorded","The 1900 household places him with Matthew and Lena.","A 1900 census index records an 18-year-old Ferdinand in the Wilkes-Barre home of Matthew and Lena Kramer. Later records follow an older Ferdinand through rope work and a 1940 owned home.","His precise birth date and the Matthew/Matthias identity need original-record comparison.","Wilkes-Barre, Pennsylvania",["Ferdinand Kramer (c. 1882)"],[["1900 census household","https://www.myheritage.com/research/record-10131-47210375/ferdinand-kramer-in-1900-united-states-federal-census?s=OYYV7ARRCL4FQTYCDTGIPASUAVZSK7I"]],"branches/kramer.md"),
  item("weatherford-marriage",1884,"1884","George Weatherford and Ella Lumpkins marry","weatherford","Marriage","recorded","A Virginia register establishes this older Weatherford couple.","Their Pittsylvania County marriage is a record-backed step in Ashley's paternal Weatherford line. Son Doctor Duffy's later death certificate identifies this family generation.","George's parents conflict between records; no immigrant arrival is identified.","Pittsylvania County, Virginia",["George C. Weatherford","Ella Lumpkins"],[["Virginia marriage index","https://www.familysearch.org/ark:/61903/1:1:6NJ1-VGMH?lang=en"]],"branches/weatherford.md"),
  item("duffy-birth",1890,"1890","Doctor Duffy Weatherford is born","weatherford","Birth","recorded","His death certificate gives a North Carolina birthplace.","The 1966 original certificate reports Duffy's 1890 birth in Caswell County and names his parents. The 1930 census later places his young son Garnett in the family home.","Birth information on a death certificate came from an informant; seek a contemporary birth record.","Caswell County, North Carolina",["Doctor Duffy Weatherford"],[["Original death certificate","https://www.familysearch.org/ark:/61903/3:1:3Q9M-C95D-9HD1?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQVRZ-2C68&action=view&lang=en"]],"branches/weatherford.md"),
  item("ferdinand-louis-birth",1913,"24 Aug 1913","Ferdinand Louis Kramer is born","kramer","Birth","recorded","The state index names a Bosch mother.","Pennsylvania's birth index records Ferdinand Kramer in Wilkes-Barre on this date, mother ‘Bosch R.’ A 1930 household places Ferdinand L. with parents Ferdinand and Rose A. and brother Emil.","The index omits middle name and father; his direct link to Fred's later obituary would benefit from a full certificate.","Wilkes-Barre, Pennsylvania",["Ferdinand Louis Kramer (1913)"],[["1913 state birth index","https://www.pa.gov/content/dam/copapwp-pagov/en/phmc/documents/archives/research-online/documents/1913-K.PDF#page=323"]],"branches/kramer.md"),
  item("emil-birth",1915,"21 Dec 1915","Emil Carl Kramer is born","kramer","Birth","recorded","He later became a rope strander, machinist and Army serviceman.","Emil's signed 1940 draft card gives his birth and father Ferdinand; his 1941 marriage form names mother Rose Bosch. He was Ferdinand Louis's brother in the 1930 census.","His obituary reports wartime awards, but the military unit and precise awards still need a service record.","Wilkes-Barre, Pennsylvania",["Emil Carl Kramer"],[["Signed draft card","https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSW4-4QGH-W?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQ2SF-63JK&action=view&lang=en"]],"branches/kramer.md"),
  item("tancy-marriage",1918,"1918","William E. Blevins marries Tancy B. Barker","smith","Marriage","recorded","The name Tancy persists in Ashley's family memory.","A Sullivan County register records this marriage. Justin and Ashley recognize Tancy Blanche as a likely namesake of Ashley's sister.","William Howard Blevins's proposed parent-child link to William E. is not yet proved, so the exact namesake relationship is open.","Sullivan County, Tennessee",["William Elkanah Blevins","Tancy Blanche Barker"],[["Marriage register index","https://www.familysearch.org/ark:/61903/1:1:QKH7-PCBN?lang=en"]],"branches/blevins-deep-lineage.md"),
  item("ada-mabel",1919,"31 Jan–12 Feb 1919, reported","Pearl is born; Ada dies twelve days later","miller","Birth","family","A memoir and memorial preserve the loss behind Pearl's Wilson upbringing.","Paulene Miller Beach said Mabel/Pearl was born on 31 January 1919 in ‘Muncy Vally, Lycoming County’ and that birth mother Ada died about two weeks later. Ada's memorial gives 12 February, twelve days after Pearl's reported birth. Wilson relatives then raised Pearl, according to Paulene.","Today's Muncy Valley is in Sullivan County; Muncy is in Lycoming. Paulene said influenza, while the memorial's biography says pneumonia. Original birth, death and guardianship records are needed to settle locality, cause and parentage.","Muncy Valley, Pennsylvania (memoir; county mismatch)",["Ada Corderman Reese","Mabel Louella Reese / Velma Pearl Wilson"],[["Paulene Miller Beach memoir","https://bhaven.org/paulene/life-journey"],["Ada memorial","https://www.findagrave.com/memorial/89675425"],["Place-sequence map",ROOT+"context/family-place-sequences.md"]],"branches/miller-gower-reese.md#the-1919-disruption"),
  item("grace-reese-obituary-1997",1997,"22 Aug 1997 obituary index","Grace's obituary names her sister Pearl","miller","Research","proposed","A later family notice joins Pearl Miller to William and Ada Reese.","A transcription and derived index for Grace E. Reese Smith's obituary name parents William H. and Ada A. Reese, and sisters Pearl Miller, Hazel Lechler and Ruth Ritter. It independently supports Paulene's sibling list.","The printed newspaper original has not been read, and Pearl's own birth and Wilson guardianship records are still missing.","Muncy Valley / Sunbury, Pennsylvania",["Grace E. Reese Smith","Pearl Miller","William H. Reese","Ada A. Reese"],[["Obituary transcription and index","https://www.our-royal-titled-noble-and-commoner-ancestors.com/lundahlbower/p177.htm"]],"branches/miller-gower-reese.md#the-1919-disruption"),
  item("paulene-name-1941",1941,"7 Mar 1941, memoir date","Paulene Miller gets a name meant for Paul","miller","Birth","family","The younger Paul Miller inherited the name his parents had first chosen for her.","In her memoir, Paulene says Lester and Mabel expected a boy and planned to name the baby Paul. When she arrived, they adapted it to Paulene; she joked that her younger brother Paul was the one she was named after. She also recalled her father ice skating while they waited for the midwife.","Paulene's date, the doctor's reported misspelling and the birth scene come from her later account; compare her birth certificate before treating them as independently verified.","Berwick, Pennsylvania",["Paulene Fay Miller Beach","Paul Miller","Lester Edmond Miller","Mabel/Pearl Reese Wilson Miller"],[["Paulene's Life Journey","https://bhaven.org/paulene/life-journey"]],"branches/miller-gower-reese.md#small-stories-paulene-preserved"),
  item("miller-homestead-1954",1954,"1954, memoir account","The Miller homestead is reportedly sold","miller","Home","family","Paulene remembers a $1,500 sale after Mary Gower Miller's death.","Paulene says that after grandmother Mary died, other heirs sold the Berwick house for $1,500 and Lester's household received no proceeds despite caring for her. Paulene and Marqueen then pooled babysitting money to buy their parents a dinette set for the next apartment.","The price, legal ownership and distribution need the deed and estate file. A reported sale is not proof of family net worth or a lost fortune.","Berwick, Pennsylvania",["Mary Emma Gower Miller","Lester Edmond Miller","Mabel/Pearl Reese Wilson Miller","Paulene Miller Beach","Marqueen Miller"],[["Paulene's Life Journey","https://bhaven.org/paulene/life-journey"]],"branches/miller-gower-reese.md#small-stories-paulene-preserved"),
  item("cordaro-photo-estimate",1925,"c. 1915–1935, visual estimate","An unidentified Cordaro family portrait","cordaro","Research","proposed","A studio portrait may date to the 1920s, but no original date is known.","Justin identifies the image as Cordaro family and guessed the 1930s. Formal dress, the pale bow or collar, and a child's short trousers fit a broad early-twentieth-century period. A 1920s center is only a low-confidence visual guess.","The people, location and exact date are unknown. Image wear cannot date the exposure, and no evidence places it in Sutera or identifies the passport holder.","Location unknown",["Unidentified Cordaro family group"],[["Family photograph",ROOT+"sources/family/cordaro-family-portrait-unidentified.jpg"],["Sutera map",ROOT+"maps/cordaro-sutera-places.svg"]],"branches/cordaro-passport-lead.md"),
  item("garnett-birth",1927,"8 Mar 1927","Garnett Burnell Weatherford Sr. is born","weatherford","Birth","recorded","His own registration card gives a Pittsylvania County birthplace.","The signed 1946 card gives his date and an honorable Navy discharge; the 1930 census places him with parents Doctor Duffy and Annie.","A later obituary says Danville rather than Pittsylvania County; these may describe nearby places, but the exact birthplace needs a birth record.","Pittsylvania County, Virginia",["Garnett Burnell Weatherford Sr."],[["Original 1946 card","https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSZX-KJ56?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQ2W5-YQRZ&action=view&lang=en"]],"branches/weatherford.md"),
  item("blevins-hines-marriage",1931,"27 Aug 1931","William Howard Blevins marries Mary Elizabeth Hines","smith","Marriage","recorded","A Bristol-area couple later appears in Gladys's family records.","The original Sullivan County license names William H. Blevins and Mary E. Hines. Their 1940 household includes daughter Gladys, later Alice Smith's mother.","The license does not name William's parents; his proposed William Elkanah parentage remains open.","Sullivan County, Tennessee",["William Howard Blevins","Mary Elizabeth Hines"],[["Original marriage-license index","https://www.familysearch.org/ark:/61903/1:1:QKH7-PC1M?lang=en"]],"branches/smith.md"),
  item("cordaro-caucci-marriage",1938,"30 Apr 1938","Joseph Cordaro and Dena Caucci marry","cordaro","Marriage","recorded","Their application names all four parents.","Joseph, born in West Wyoming, worked as a laborer. Dena was born in Jessup. The original county form names Joseph's parents Anthony Cordaro and Petra Magro, and Dena's parents Joseph Caucci and Anna Belardinelli.","Handwritten surname spellings vary in the index. This record does not name Patricia's reported sisters.","Jessup, Pennsylvania",["Joseph Cordaro","Dena / Dina Caucci","Anthony Cordaro","Pietra Magro","Joseph Caucci","Anna Belardinelli"],[["Original county application",ROOT+"sources/records/cordaro-caucci-marriage-1938.jpg"]],"branches/cordaro-passport-lead.md"),
  item("fred-birth",1939,"8 Jul 1939","Fred / Ferdinand Francis Kramer is born","kramer","Birth","recorded","His obituary names both parents.","Fred's obituary gives Wilkes-Barre birth and names Ferdinand Louis Kramer and Mary Andrews. A 1950 census places a son Ferdinand with the matching household.","The 1950 enumerator's age differs by one year; use Fred's precise obituary date with that caveat.","Wilkes-Barre, Pennsylvania",["Fred / Ferdinand Francis Kramer (1939)"],[["Fred's obituary","https://www.legacy.com/person/ferdinand-francis-kramer-%28fred%29-52588560"]],"branches/kramer.md"),
  item("patricia-birth",1940,"9 Jun 1940","Patricia Cordaro is born in Kingston","cordaro","Birth","recorded","Her later marriage application gives the date, birthplace and both parents.","Patricia's 1962 Luzerne County marriage form reports Joseph Cordaro and Dina Caucci as her parents. Joseph and Dina were living in nearby West Wyoming in the 1940 census before her birth.","The birth date is an applicant statement on a later record; a birth or baptism certificate would independently verify it.","Kingston, Luzerne County, Pennsylvania",["Patricia Cordaro","Joseph Cordaro","Dina Caucci"],[["Luzerne County marriage archive","https://www.searchiqs.com/paluze/"],["1940 census","https://www.familysearch.org/ark:/61903/1:1:KQ7W-L64?lang=en"]],"branches/cordaro-passport-lead.md"),
  item("cordaro-kramer-marriage",1962,"22 Nov 1962","Patricia Cordaro marries Fred Kramer","cordaro","Marriage","recorded","The original county application identifies her parents.","Patricia, a secretary, married Fred, a shoe-factory employee, in West Wyoming. Her application names Joseph Cordaro and Dina Caucci. Find Marriages book 191, page 2785 in the Luzerne County archive.","A paid download is optional; the county image can be viewed free. The record does not establish a link to the Sutera passport holder.","West Wyoming, Pennsylvania",["Patricia Cordaro","Fred / Ferdinand Francis Kramer (1939)","Joseph Cordaro","Dina Caucci"],[["Luzerne County marriage archive","https://www.searchiqs.com/paluze/"],["Archive instructions","https://www.luzernecounty.org/614/Register-of-Wills"]],"branches/cordaro-passport-lead.md"),
  item("cordaro-kramer-obit",2023,"12 Aug 2023","Patricia Cordaro's Kramer connection is named","cordaro","Research","recorded","Fred Kramer's obituary names wife Patricia Cordaro and son Paul.","The indexed Times Leader obituary gives Patricia Anne Marie Cordaro Kramer as Fred's wife and Paul Kramer among their children. Justin identifies Paul as his father and names Joan, Mary and Toni Cordaro as Patricia's sisters.","Patricia's parents are not named in this obituary; neither her birth/death status nor the passport holder's relationship is established.","Wilkes-Barre, Pennsylvania",["Patricia Anne Marie Cordaro Kramer","Ferdinand Francis Kramer","Paul Kramer","Joan Cordaro","Mary Cordaro","Toni Cordaro"],[["Obituary index","https://www.familysearch.org/ark:/61903/1:1:6L83-L29V?lang=en"],["Family account",ROOT+"branches/cordaro-passport-lead.md"]],"branches/cordaro-passport-lead.md"),
  item("kramer-1940-work",1940,"1940 census; 1939 wages","Ferdinand’s rope work and home are recorded","kramer","Work","recorded","A concrete, limited economic snapshot.","The older Ferdinand reported 52 weeks as a wire-rope foreman and $1,996 in 1939 wages, plus an owned home estimated at $2,400. A resident son worked as a wire-rope winder and reported $1,234; daughter Hilda attended school.","Census wages and a home estimate are not household net worth or proof of inherited assets.","146 Prospect Street, Wilkes-Barre",["Ferdinand Kramer (c. 1882)","Emil Carl Kramer","Hilda Kramer"],[["Original 1940 census","https://catalog.archives.gov/medialz/census-1940/T627/PA/m-t0627-03563/m-t0627-03563-00103.jpg"]],"branches/kramer.md"),
  item("emil-1940-draft",1940,"16 Oct 1940","Emil Carl Kramer signs his draft card","kramer","Military","recorded","The two-sided card gives a signature, family contact and employer.","Emil registered while living at 146 Prospect Street. He gave his father Ferdinand as contact and American Chain & Cable as employer. The saved image includes both sides of the card.","Registration did not mean he had entered military service; an Army index records later enlistment in 1943.","Wilkes-Barre, Pennsylvania",["Emil Carl Kramer","Ferdinand Kramer (c. 1882)"],[["Saved signed card",ROOT+"sources/records/emil-carl-kramer-draft-registration-1940.jpg"],["FamilySearch original","https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSW4-4QGH-W?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AQ2SF-63JK&action=view&lang=en"]],"branches/kramer.md"),
  item("emil-victoria-1941",1941,"12 Feb 1941","Emil Kramer marries Victoria Giampietro","kramer","Marriage","recorded","A signed application identifies his parents and rope-factory job.","The right page of the saved Luzerne County application names Emil's parents Ferdinand and Rose Bosch and calls him a strander. It names Victoria Giampietro as his bride.","The left page belongs to another couple; read only the right page for Emil and Victoria.","Luzerne County, Pennsylvania",["Emil Carl Kramer","Victoria Giampietro","Ferdinand Kramer (c. 1882)","Rose Bosch Kramer"],[["Saved application",ROOT+"sources/records/emil-kramer-victoria-giampietro-marriage-1941.jpg"],["FamilySearch original","https://www.familysearch.org/ark:/61903/3:1:33S7-9PR4-97SS?view=index&personArk=%2Fark%3A%2F61903%2F1%3A1%3AKHFH-X3X&action=view&lang=en"]],"branches/kramer.md"),
  item("emil-army",1943,"27 Jul 1943","Emil Carl Kramer enters the Army","kramer","Military","recorded","An enlistment index confirms wartime entry.","Emil's 1940 draft card named American Chain & Cable as his employer; his 1941 marriage called him a strander. The 1943 Army enlistment index establishes entry as a selectee/private.","The index does not establish his unit, overseas service or medals.","Wilkes-Barre, Pennsylvania",["Emil Carl Kramer"],[["Army enlistment index","https://www.familysearch.org/ark:/61903/1:1:K8TZ-8YY?lang=en"]],"branches/kramer.md"),
  item("garnett-navy",1946,"By 1946","Garnett’s Navy discharge is recorded","weatherford","Military","recorded","His card says ‘Honorable Discharge Navy.’","Garnett's registration card confirms a Navy discharge by 1946. His later obituary reports service in the Pacific during World War II. Justin says Garnett joined at 17 after misstating his age; that detail is a family account.","The records found do not establish an enlistment date or declared age, ship, rank, Pacific stations or battles.","Virginia / Pacific theater, exact station unknown",["Garnett Burnell Weatherford Sr."],[["Original 1946 card","https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSZX-KJ56?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQ2W5-YQRZ&action=view&lang=en"]],"branches/weatherford.md"),
  item("kramer-1950-homes",1950,"1950 census","Two Ferdinand households appear separately","kramer","Work","recorded","The younger worked at a wire-rope works; the elder was widowed.","The younger Ferdinand lived with wife Mary, sons Fred and Paul, and father-in-law Frank Andrews; he was a machine operator. The elder lived with daughter Hilda and son-in-law Joseph Wolosz.","The sampled census does not provide a whole-family wealth figure or explain property transfer.","Wilkes-Barre, Pennsylvania",["Ferdinand Kramer (c. 1882)","Ferdinand Louis Kramer (1913)","Mary Andrews Kramer"],[["Younger household","https://1950census.archives.gov/iiif/2/1950census%2F43290879-Pennsylvania%2F43290879-Pennsylvania-135713%2F43290879-Pennsylvania-135713-0005.jpg/full/full/0/default.jpg"],["Elder household","https://1950census.archives.gov/iiif/2/1950census%2F43290879-Pennsylvania%2F43290879-Pennsylvania-135659%2F43290879-Pennsylvania-135659-0014.jpg/full/full/0/default.jpg"]],"branches/kramer.md"),
  item("older-ferdinand-1951",1951,"5 Jun 1951","Ferdinand Kramer, the older foreman, dies","kramer","Death","recorded","His certificate links his rope work to parents named by the informant.","The Pennsylvania certificate identifies Ferdinand, age 68, as a retired wire-rope foreman. Informant Emil C. Kramer gave father Matthew Kramer and mother ‘Matilda Dasque.’ The same image is misfiled on the FamilySearch profile of his son Ferdinand Louis.","‘Matilda Dasque’ conflicts with the chart's ‘Magdalena Disque’ and census ‘Lena’; do not merge these names without earlier records.","Danville, Pennsylvania",["Ferdinand Kramer (c. 1882)","Emil Carl Kramer","Matthew Kramer","Matilda Dasque, as written"],[["Saved death certificate",ROOT+"sources/records/ferdinand-kramer-1882-death-certificate-1951.jpg"],["FamilySearch memory","https://www.familysearch.org/memories/memory/122055960"]],"branches/kramer.md"),
  item("garnett-florence",1954,"16 Jan 1954, license index","Garnett and Florence Morrison are paired","weatherford","Marriage","recorded","A Fairfax marriage index gives a date and names.","The county brides' index pairs Florence Ruth Morrison with ‘Garrett Burnell Weatherford.’ Garnett's obituary later says they had been married 53 years.","The index spells Garrett, unlike Garnett's other records, and may give a license rather than ceremony date. Read the original.","Fairfax County, Virginia",["Garnett Burnell Weatherford Sr.","Florence Ruth Morrison"],[["Fairfax marriage index","https://www.fairfaxcounty.gov/circuit/sites/circuit/files/assets/documents/pdf/hrc/marriage-book-index-1853-1957-brides.pdf"]],"branches/weatherford.md"),
  item("smith-house-built",1960,"1960","The Miller Drive Smith house is built","smith","Home","recorded","The parcel later becomes a family landmark.","Fairfax County dates the house at 6330 Miller Drive to 1960. Alice's later marriage return records her at this address, and family account places her parents James and Gladys Smith there.","A construction year does not establish the Smiths' move-in date or who paid for the house.","Franconia, Fairfax County, Virginia",["James Allen Smith","Gladys Louise Blevins Smith"],[["Fairfax parcel lookup","https://icare.fairfaxcounty.gov/ffxcare/search/commonsearch.aspx?mode=address"]],"branches/weatherford-smith.md"),
  item("duffy-death",1966,"1966","Doctor Duffy Weatherford dies","weatherford","Death","recorded","His certificate anchors an older Weatherford generation.","The original Virginia death certificate provides dates, place and reported parents. It distinguishes Duffy from other men named Doctor or D.D. Weatherford in derivative trees.","Informant-supplied birth facts still merit comparison with earlier records.","Danville, Virginia",["Doctor Duffy Weatherford"],[["Original death certificate","https://www.familysearch.org/ark:/61903/3:1:3Q9M-C95D-9HD1?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQVRZ-2C68&action=view&lang=en"]],"branches/weatherford.md"),
  item("annie-death",1969,"1969","Annie Neathery Weatherford dies","weatherford","Death","recorded","Her certificate names her parents.","Annie's original death certificate reports parents John R. Neathery and Annie Phelps, giving Ashley's Weatherford side two more names to follow.","The parents' own birth, marriage and death records remain to be found.","Danville, Virginia",["Annie Neathery Weatherford","John R. Neathery","Annie Phelps"],[["Original death certificate","https://www.familysearch.org/ark:/61903/3:1:3Q9M-C95D-49MW-W?view=index&personArk=%2Fark%3A%2F61903%2F1%3AQVYL-N4BR&action=view&lang=en"]],"branches/weatherford.md"),
  item("bridon-change",1972,"1972","Bridon acquires ACCO wire-rope assets","context","History","context","The Bridon-American name belongs to a later industrial chapter.","A government industry study dates Bridon's acquisition of American Chain & Cable rope assets to 1972. Emil's 1940 card names ACCO, and Ferdinand Louis's obituary reports a career at ACCO followed by Bridon Industries.","This company history and the younger son's obituary do not establish the older Ferdinand's employer.","Wilkes-Barre area, Pennsylvania",["Emil Carl Kramer"],[["Government industry study","https://publications.gc.ca/collections/collection_2019/isde-ised/RG54-1-4-eng.pdf"]],"branches/kramer.md"),
  item("younger-ferdinand-1976",1976,"Mar 1976","Ferdinand Louis Kramer's obituary traces his career","kramer","Death","recorded","A family notice names his schools and a long rope-industry career.","The clipping reports G.A.R. High School, National Radio Institute classes in Washington, over 44 years at American Chain & Cable, later Bridon Industries, and retirement in 1975. It names wife Mary Andrews, sons Fred and Paul, brother Emil and sister Hilda.","The newspaper masthead is absent from the saved clipping; education and employment are family-reported, pending school and personnel records.","Wilkes-Barre area, Pennsylvania",["Ferdinand Louis Kramer (1913)","Mary Andrews Kramer","Fred Kramer","Paul Kramer","Emil Carl Kramer","Hilda Kramer Wolosz"],[["Saved obituary clipping",ROOT+"sources/records/ferdinand-louis-kramer-obituary-1976.jpg"],["FamilySearch memory","https://www.familysearch.org/memories/memory/122055961"]],"branches/kramer.md"),
  item("mabel-paulene-cruise",1999,"Before 31 Jan 1999, if Mabel's memoir birth date is right","Paul Miller sends Mabel and Paulene on a cruise","miller","Travel","family","Mabel later called it her favorite trip.","Paulene recalled that her brother Paul Miller, Justin's maternal grandfather, sent their mother Mabel/Pearl and Paulene on an island cruise before Mabel's 80th birthday. The family held a birthday party after they returned.","The 1999 bound is calculated from Mabel's reported 31 January 1919 birth, not a dated travel record. The memoir does not name the ship, islands, departure date or how Paul arranged or paid for the trip.","Islands not specified",["Paul Miller","Mabel/Pearl Reese Wilson Miller","Paulene Miller Beach"],[["Paulene's first-person memoir","https://bhaven.org/paulene/life-journey"],["Family moments",ROOT+"branches/miller-gower-reese.md#small-stories-paulene-preserved"]],"branches/miller-gower-reese.md#small-stories-paulene-preserved"),
  item("emil-2004",2004,"2004","Emil Carl Kramer's obituary recounts war and work","kramer","Death","recorded","The clipping reports a Purple Heart and decades as a machinist.","Emil's obituary says he served in the Army's Middle Eastern Theater, received a Purple Heart and ‘three Bronze Stars,’ and retired as an ACCO machinist after 36 years. It also names wife Victoria and sister Hilda.","The wording ‘Bronze Stars’ may mean medals or bronze campaign/service stars. A discharge or award record is needed to resolve that and confirm the unit and wounds.","Wilkes-Barre area, Pennsylvania",["Emil Carl Kramer","Victoria Giampietro Kramer","Hilda Kramer Wolosz"],[["Saved obituary clipping",ROOT+"sources/records/emil-carl-kramer-obituary-2004.jpg"],["FamilySearch memory","https://www.familysearch.org/memories/memory/122056249"]],"branches/kramer.md"),
  item("pearl-miller-2008",2008,"7 Apr 2008","Pearl Miller's program preserves a portrait and family memories","miller","Death","recorded","Her grandson remembered a home full of cousins, music and travel.","A family funeral program gives Velma ‘Pearl’ Miller's birth and death as 31 January 1919 and 7 April 2008. Michael Beach recalled band practice with Lester, Carl and Fred, motorhome trips across the country, and a campsite bear she wanted to hug.","The program confirms her dates but does not identify her birth parents. The portrait has no exposure date; the bear anecdote is Michael's memory.","Berwick, Pennsylvania",["Velma Pearl Wilson Miller","Mabel Louella Reese, reported birth name","Michael Beach"],[["2008 program and tribute","https://bhaven.org/uploads/3/4/0/3/34038663/vol14sec2.pdf#page=1"]],"branches/miller-gower-reese.md#small-stories-paulene-preserved"),
  item("hilda-portrait-2020",2020,"2020 remembrance; photo undated","Hilda Kramer Wolosz in a family portrait","kramer","Research","family","A contributor-tagged image shows the older Ferdinand's daughter.","A FamilySearch memory uploaded in 2021 is tagged as Hilda M. Kramer Wolosz. Her obituary names parents Ferdinand and Rose Bosch Kramer and records her 2020 death. The portrait itself has no date.","The portrait identity is contributor-supplied. Its 2021 upload date and this 2020 timeline placement are not dates of exposure.","Place of exposure unknown",["Hilda M. Kramer Wolosz","Ferdinand Kramer (c. 1882)","Rose Bosch Kramer"],[["Saved family portrait",ROOT+"sources/family/hilda-kramer-wolosz-portrait-undated.jpg"],["FamilySearch memory","https://www.familysearch.org/memories/memory/122056242"],["Hilda's obituary","https://www.legacy.com/us/obituaries/citizensvoice/name/hilda-wolosz-obituary?id=7822560"]],"branches/kramer.md"),
  item("franconia-racing",1979,"1979","Drag racing reported near the Franconia families","context","History","context","A contemporary report helps explain a family memory of danger.","A Washington Post report described illegal races and arrests in nearby Fullerton Industrial Park. Fairfax County was also growing rapidly during John and Alice's school years.","The report documents a nearby scene, not that John or Alice attended a race or witnessed an incident.","Springfield / Franconia, Virginia",["John Weatherford Sr.","Alice Smith Weatherford"],[["Contemporary report","https://www.washingtonpost.com/archive/local/1979/11/18/a-jump-on-dragsters/0343da14-ade3-491c-afc9-af454c2e9c62/"]],"context/franconia-growing-up.md"),
  item("john-alice-marriage",1986,"1986","John Weatherford and Alice Smith marry","smith","Marriage","recorded","One record joins the two Fairfax families.","Their Fairfax marriage return names Alice's parents James Allen Smith and Gladys Louise Blevins, and gives the couple's Miller Drive residences shortly before marriage.","Earlier Smith and Blevins generations still require separate records; the marriage does not establish an immigrant date.","Fairfax County, Virginia",["John Gordon Weatherford Sr.","Alice Marie Smith Weatherford"],[["Original marriage return index","https://www.familysearch.org/ark:/61903/1:1:QK9V-J612?lang=en"]],"branches/weatherford-smith.md"),
  item("colette-built",1989,"1989","The Colette Drive house is constructed","smith","Home","recorded","The later Weatherford home takes shape.","Fairfax County's parcel history dates construction to 1989. John and Alice's recorded purchase came later, in 1993.","Construction is not evidence that the family lived there in 1989.","Franconia, Fairfax County, Virginia",["John Weatherford Sr.","Alice Smith Weatherford"],[["Fairfax parcel lookup","https://icare.fairfaxcounty.gov/ffxcare/search/commonsearch.aspx?mode=address"]],"branches/weatherford-smith.md"),
  item("colette-purchase",1993,"1993","John and Alice buy the Colette Drive home","smith","Home","recorded","A $255,000 verified sale appears in county records.","The parcel history records the 1993 purchase. It is a property transaction, not an income or net-worth statement; mortgage and later equity are unknown.","Do not infer inheritance or family wealth from purchase price alone.","Franconia, Fairfax County, Virginia",["John Weatherford Sr.","Alice Smith Weatherford"],[["Fairfax parcel lookup","https://icare.fairfaxcounty.gov/ffxcare/search/commonsearch.aspx?mode=address"]],"branches/weatherford-smith.md"),
  item("garnett-death",2007,"27 Jun 2007","Garnett Weatherford Sr. dies","weatherford","Death","recorded","His obituary remembers Navy and transit service.","The obituary reports Pacific service in the Navy and later work for AB&W and Metro bus systems. His personnel records would tell a much more precise wartime story.","The obituary does not establish a ship, battle, rank or full military timeline.","Northern Virginia",["Garnett Burnell Weatherford Sr."],[["Garnett's obituary","https://www.washingtonpost.com/archive/local/2007/07/03/obituaries/43ba782a-181c-4c59-a78e-7d361d86bf4a/"]],"branches/weatherford.md"),
  item("gladys-death",2008,"2008","Gladys Blevins Smith’s memorial names five children","smith","Death","recorded","A published family notice confirms Alice’s sibling group.","The memorial names Jane, James Howard, Timothy, Alice and Carolyn as Gladys's children. Original marriage returns independently connect Jane, James Howard and Alice to the same parents.","Birth order and some individual dates remain open.","Northern Virginia",["Gladys Louise Blevins Smith","Alice Smith Weatherford"],[["Gladys memorial","https://www.findagrave.com/memorial/45796517/gladys_louise-smith"]],"branches/smith.md"),
  item("fred-death",2023,"29 Jul 2023","Fred Kramer’s obituary ties three generations","kramer","Death","recorded","It identifies his parents, brother and service story.","The notice names Ferdinand Louis and Mary Andrews Kramer as Fred's parents. It reports Army Reserve service and Techneglas work, connecting household records to a remembered life.","An obituary is a family report; verify disputed early vital details against original certificates.","Wilkes-Barre, Pennsylvania",["Fred / Ferdinand Francis Kramer (1939)"],[["Fred's obituary","https://www.legacy.com/person/ferdinand-francis-kramer-%28fred%29-52588560"]],"branches/kramer.md"),
  item("monty-birth",2025,"17 Apr 2025","Monty the Pembroke Welsh Corgi is born","monty","Birth","recorded","His AKC certificate opens a different family tree.","The photographed registration certificate names him Triple H Knight Shadow From Cedar Springs, with sire GCHB CH Triple H Bechanci Knight to Remember and dam Triple H Shadow Dancer RN.","The certificate gives birth and registered parentage, but not his arrival date in Justin's home or older ancestors beyond those checked separately.","Birthplace not stated",["Monty","Triple H Bechanci Knight to Remember","Triple H Shadow Dancer RN"],[["Family AKC certificate",ROOT+"sources/pets/monty-akc-certificate.jpg"]],"branches/monty.md"),
  item("kramers-muncy-now",2026,"Now, family-supplied","Melissa and Paul Kramer live in Muncy Township","miller","Home","family","Their home brings the family story back near Mabel's reported birthplace.","Justin says his parents Melissa Miller Kramer and Paul Kramer live in the Muncy postal area. The Census geocoder places the address in Muncy Township, Lycoming County. Melissa is the daughter of Paul Miller, who is Mabel/Pearl's son. This is a regional return across generations from Muncy Valley through Berwick to today's Muncy area.","Muncy Valley and Muncy Township are different places; Mabel's exact 1919 locality and the later move dates need records. The map marks a township area, not a living person's house. Paul Miller and Paul Kramer are different people.","Muncy Township, Lycoming County, Pennsylvania",["Paul Miller","Melissa Miller Kramer","Paul Kramer","Mabel/Pearl Reese Wilson Miller"],[["Family-supplied place and map",ROOT+"context/family-place-sequences.md"],["Muncy Valley locality","https://www.sullivancountypa.gov/municipalities/shrewsbury-township"]],"context/family-place-sequences.md")
];

const MEDIA = {
  "ada-corderman-1900": ["sources/records/ada-corderman-wilson-household-1900.jpg", "1900 census page with Ada A. Corderman and Rosa E. Corderman in the Wilson household", "Original census · lines 25–31. Ada's link to Mabel is unproved."],
  "weatherford-oakes-1855": ["sources/records/halifax-weatherford-oakes-marriage-register-1855.jpg", "Full Halifax County marriage-register spread, 1855", "Original register spread · 1855. Open for the full-size handwriting."],
  "cordaro-photo-estimate": ["sources/family/cordaro-family-portrait-unidentified.jpg", "Unidentified Cordaro family group portrait", "Family photograph · people and exposure date unknown."],
  "cordaro-caucci-marriage": ["sources/records/cordaro-caucci-marriage-1938.jpg", "Joseph Cordaro and Dena Caucci marriage application", "Original application · the couple is on the right-hand page."],
  "emil-1940-draft": ["sources/records/emil-carl-kramer-draft-registration-1940.jpg", "Front and back of Emil Carl Kramer's signed draft card", "Signed draft card · 1940. Open to read both sides."],
  "emil-victoria-1941": ["sources/records/emil-kramer-victoria-giampietro-marriage-1941.jpg", "Emil Kramer and Victoria Giampietro marriage application", "Original application · Emil and Victoria are on the right-hand page."],
  "older-ferdinand-1951": ["sources/records/ferdinand-kramer-1882-death-certificate-1951.jpg", "1951 death certificate of Ferdinand Kramer born about 1882", "Original certificate · misattached to his namesake son's FamilySearch profile."],
  "younger-ferdinand-1976": ["sources/records/ferdinand-louis-kramer-obituary-1976.jpg", "1976 obituary clipping for Ferdinand Louis Kramer", "Obituary clipping · school and work details reported by family."],
  "emil-2004": ["sources/records/emil-carl-kramer-obituary-2004.jpg", "2004 obituary clipping for Emil Carl Kramer", "Obituary clipping · military awards need a service record."],
  "hilda-portrait-2020": ["sources/family/hilda-kramer-wolosz-portrait-undated.jpg", "Undated portrait tagged as Hilda Kramer Wolosz", "Contributor-tagged portrait · exposure date unknown."]
};

const $ = id => document.getElementById(id);
const state = { branch: "all", type: "all", era: "all", query: "", selected: null };
const eras = ["all","1600s","1700s","1800s","1900s","2000s"];
const el = (tag, className, value) => { const node = document.createElement(tag); if (className) node.className = className; if (value != null) node.textContent = value; return node; };
function link(label, href) { const a = el("a", "", label + " ↗"); a.href = href; if (/^https?:/.test(href)) { a.target = "_blank"; a.rel = "noopener noreferrer"; } return a; }
function visible() {
  return EVENTS.filter(e => (state.branch === "all" || e.branch === state.branch)
    && (state.type === "all" || e.type === state.type)
    && (state.era === "all" || Math.floor(e.year / 100) * 100 === Number(state.era.slice(0,4)))
    && (!state.query || [e.title,e.summary,e.detail,e.place,...e.people,BRANCHES[e.branch].label].join(" ").toLowerCase().includes(state.query)))
    .sort((a,b) => a.year - b.year || a.title.localeCompare(b.title));
}
function renderEras() {
  const host = $("eras"); host.replaceChildren();
  eras.forEach(era => {
    const count = era === "all" ? EVENTS.length : EVENTS.filter(e => Math.floor(e.year / 100) * 100 === Number(era.slice(0,4))).length;
    const b = el("button", state.era === era ? "active" : "", era === "all" ? "All years" : era);
    b.type = "button"; b.setAttribute("aria-pressed", String(state.era === era));
    b.append(el("small", "", String(count)));
    b.addEventListener("click", () => { state.era = era; render(); }); host.append(b);
  });
}
function renderList(rows) {
  const host = $("event-list"); host.replaceChildren(); $("empty").hidden = rows.length > 0;
  rows.forEach(e => {
    const button = el("button", "event" + (e.id === state.selected ? " selected" : ""));
    button.type = "button"; button.style.setProperty("--branch", BRANCHES[e.branch].color);
    button.setAttribute("aria-label", e.date + ": " + e.title + ". Open details.");
    button.setAttribute("aria-pressed", String(e.id === state.selected));
    const top = el("span", "event-top"); top.append(el("span", "event-year", e.date), el("span", "event-branch", BRANCHES[e.branch].label));
    const tags = el("span", "event-tags"); tags.append(el("span", "tag", e.type), el("span", "tag evidence-" + e.evidence, e.evidence === "family" ? "Family account" : e.evidence[0].toUpperCase() + e.evidence.slice(1)));
    if (MEDIA[e.id]) tags.append(el("span", "tag", "View image"));
    button.append(top, el("span", "event-title", e.title), el("span", "event-summary", e.summary), tags);
    button.addEventListener("click", () => { state.selected = e.id; location.hash = e.id; render(); if (matchMedia("(max-width:850px)").matches) $("detail").scrollIntoView({behavior:"smooth",block:"start"}); });
    host.append(button);
  });
}
function renderDetail(e) {
  const host = $("detail"); host.replaceChildren(); if (!e) { host.append(el("p", "detail-body", "Choose another filter to see an event.")); return; }
  host.style.setProperty("--branch", BRANCHES[e.branch].color);
  const top = el("div", "detail-top"); top.append(el("p", "eyebrow", BRANCHES[e.branch].label + " · " + e.type), el("h2", "", e.title), el("span", "when", e.date));
  const body = el("div", "detail-body"); body.append(el("p", "", e.detail));
  if (MEDIA[e.id]) {
    const [path, alt, caption] = MEDIA[e.id];
    const figure = el("figure", "event-media");
    const imageLink = el("a"); imageLink.href = ROOT + path;
    const image = el("img"); image.src = ROOT + path; image.alt = alt; image.loading = "lazy";
    imageLink.append(image); figure.append(imageLink, el("figcaption", "", caption)); body.append(figure);
  }
  const facts = el("div", "fact-grid");
  [["Place",e.place],["Evidence",e.evidence === "family" ? "Family account" : e.evidence[0].toUpperCase()+e.evidence.slice(1)]].forEach(([name,value]) => { const f = el("div","fact"); f.append(el("b","",name),el("span","",value)); facts.append(f); });
  body.append(facts,el("p","caveat",e.caveat),el("h3","","People in this story"));
  const names = el("ul"); e.people.forEach(name => names.append(el("li","",name))); body.append(names,el("h3","","Read the evidence"));
  const sources = el("ul"); e.sources.forEach(([label,url]) => { const li = el("li"); li.append(link(label,url)); sources.append(li); }); body.append(sources);
  const actions = el("div","detail-links"); actions.append(link("Read the full story",ROOT+e.story)); body.append(actions); host.append(top,body);
}
function render() {
  renderEras(); const rows = visible();
  if (!rows.some(e => e.id === state.selected)) state.selected = rows[0]?.id || null;
  $("showing-count").textContent = rows.length + " of " + EVENTS.length + " events";
  $("filter-note").textContent = rows.length ? "Showing " + rows.length + " events from " + rows[0].year + " to " + rows[rows.length-1].year + ". Select any card to open its records." : "No events match the current filters.";
  renderList(rows); renderDetail(rows.find(e => e.id === state.selected));
}
$("total-count").textContent = EVENTS.length + " curated events";
Object.entries(BRANCHES).forEach(([key,value]) => { const option = el("option","",value.label); option.value = key; $("branch").append(option); });
TYPES.forEach(type => { const option = el("option","",type); option.value = type; $("type").append(option); });
$("search").addEventListener("input", event => { state.query = event.target.value.trim().toLowerCase(); render(); });
$("branch").addEventListener("change", event => { state.branch = event.target.value; render(); });
$("type").addEventListener("change", event => { state.type = event.target.value; render(); });
$("reset").addEventListener("click", () => { state.branch="all";state.type="all";state.era="all";state.query="";$("search").value="";$("branch").value="all";$("type").value="all";render(); });
window.addEventListener("hashchange", () => { const id = decodeURIComponent(location.hash.slice(1)); if (id === state.selected) return; if (EVENTS.some(e => e.id === id)) { state.branch="all";state.type="all";state.era="all";state.query="";$("search").value="";$("branch").value="all";$("type").value="all";state.selected=id;render(); } });
const initialId = decodeURIComponent(location.hash.slice(1)); state.selected = EVENTS.some(e => e.id === initialId) ? initialId : "kings-mountain";
render();
