import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { lines, sides } from '../site/family-lines.mjs';

const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = { recorded: 'Record-supported link', probable: 'Strong match · original bridge needed', family: 'Family account · independent bridge open', account: 'Retrospective family / biography link', lead: 'Unresolved identity or parent link' };
const pageUrl = line => `explore/lines/${line.id}.html`;
const href = (source, prefix) => prefix + source.replace(/\.md(?=$|#)/, '.html');

export function branchBrowser(prefix = '', heading = 'Choose a family line') {
  return `<section class="branch-browser" data-line-browser aria-labelledby="lines-heading"><div class="section-intro"><div><p class="eyebrow">Family lines</p><h2 id="lines-heading">${heading}</h2></div><p>Open a name for its tree, places, work and timeline. Related surnames are searchable too.</p></div><div class="line-tools"><label>Find a family line<input type="search" data-line-search placeholder="Try Raber, Balliet, Andrews…" autocomplete="off"></label><label>Family side<select data-line-side><option value="all">All family sides</option>${Object.entries(sides).map(([key,name]) => `<option value="${key}">${name}</option>`).join('')}</select></label></div><p class="line-count" data-line-count role="status">${lines.length} family lines · choose any branch below</p>${Object.entries(sides).map(([key,side]) => `<section class="line-group" data-line-group><h3>${side}</h3><div class="line-grid">${lines.filter(l => l.side === key).map(l => {
    const search = [l.name, l.aliases, l.origin, l.connection, ...l.generations.map(g=>g.names)].join(' ');
    return `<a class="line-card" data-line-card data-side="${key}" data-search="${esc(search)}" href="${prefix}${pageUrl(l)}"><span class="line-card-top">${esc(l.aliases.split(' ').slice(0,3).join(' · '))}</span><h4>${esc(l.name)}</h4><p>${esc(l.origin)}</p><span class="line-card-foot">${l.generations.length} tree cards · branch timeline <b aria-hidden="true">↗</b></span></a>`;
  }).join('')}</div></section>`).join('')}<p class="line-empty" data-line-empty hidden>No line matches yet. Try a surname, person or place, or clear the family-side filter. <a href="${prefix}explore/library.html">Search every research page ↗</a></p><noscript><p>All branches are listed below; browser search filters need JavaScript.</p></noscript></section>`;
}

export async function buildLines(output, header, searchIndex) {
  const shell = (title, description, body, prefix, script = false) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142a31"><title>${esc(title)} · Family Atlas</title><meta name="description" content="${esc(description)}"><link rel="stylesheet" href="${prefix}site.css"><link rel="stylesheet" href="${prefix}lines.css">${script ? `<script src="${prefix}branch-browser.js" defer></script>` : ''}</head><body><a class="skip" href="#main">Skip to family line</a>${header(prefix)}${body}<footer><span>Family Atlas · records, accounts and research leads are labeled.</span><a href="${prefix}explore/branches.html">All branches</a><a href="${prefix}research/sources.html">Source ledger</a><a href="${prefix}research/open-questions.html">Open questions</a></footer></body></html>`;
  const directory = `<main id="main" class="lines-main"><section class="directory-intro"><p class="eyebrow">Find your branch</p><h1>Which family line?</h1><p>Start with a surname. Each branch has a compact tree and timeline, with the places people lived and the work they did beside the generations.</p><a class="outline-link" href="family-explorer.html">See how the main paths connect ↗</a></section>${branchBrowser('../')}<section class="line-context"><h2>Following a spouse’s family?</h2><p>Use the related-line links on each branch. Andrews opens Kennedy; Cordaro opens Caucci; Raber opens Kreischer and Balliet. A family connected by marriage has its own ancestry and evidence.</p><a href="../FAMILY-TREE.html">Read the four-side family guide ↗</a><a href="../branches/monty.html">Monty’s pedigree ↗</a></section></main>`;
  await mkdir(path.join(output, 'explore', 'lines'), {recursive:true});
  await writeFile(path.join(output, 'explore', 'branches.html'), shell('Choose a family line', 'Browse Raber, Balliet, Andrews and the other family branches by surname, tree, timeline, places and work.', directory, '../', true));
  searchIndex.push({title:'Choose a family line',url:'explore/branches.html',category:'explore',text:lines.map(l=>`${l.name} ${l.aliases} ${l.origin}`).join(' ')});
  for (const l of lines) {
    const prefix = '../../';
    const tree = l.generations.map((g,i) => `<li>${i ? `<div class="tree-edge ${g.edge}"><span>${esc(labels[g.edge])}${g.edge === 'lead' ? ' · read the gap' : ''}</span></div>` : ''}<a class="compact-person" href="#generation-${i+1}"><span>${esc(g.era)}</span><strong>${esc(g.names)}</strong><small>${esc(g.place)}</small></a></li>`).join('');
    const people = l.generations.map((g,i) => `<article class="generation" id="generation-${i+1}"><p class="generation-era">${esc(g.era)}</p><h3>${esc(g.names)}</h3><dl><div><dt>Place</dt><dd>${esc(g.place)}</dd></div><div><dt>Work / learning</dt><dd>${esc(g.work)}</dd></div>${g.resources ? `<div><dt>Home / resources</dt><dd>${esc(g.resources)}</dd></div>` : ''}</dl><p>${esc(g.note)}</p><a href="${href(g.source,prefix)}">Read this generation’s evidence ↗</a></article>`).join('');
    const events = l.events.map(event => `<li><span class="event-date">${esc(event.date)}</span><div><h3>${esc(event.title)}</h3><p>${esc(event.text)}</p><a href="${href(event.source,prefix)}">Open the record or source notes ↗</a></div></li>`).join('');
    const related = l.related.map(id => lines.find(other=>other.id===id));
    if (related.some(l=>!l)) throw new Error(`Unknown related branch in ${l.id}`);
    const body = `<main id="main" class="line-main"><nav class="line-breadcrumb" aria-label="Breadcrumb"><a href="../branches.html">All family lines</a><span aria-hidden="true">/</span><span>${sides[l.side]}</span></nav><section class="line-intro"><p class="eyebrow">${sides[l.side]}</p><h1>The ${esc(l.name)} line</h1><p class="line-origin">${esc(l.origin)}</p><p>${esc(l.connection)}</p><nav class="line-section-nav" aria-label="Branch sections"><a href="#branch-tree">Small tree</a><a href="#generations">Places &amp; work</a><a href="#branch-timeline">Timeline</a><a href="#related-lines">Related lines</a><a href="#branch-records">Detailed research</a></nav></section><div class="branch-layout"><aside class="line-tree-panel" id="branch-tree"><p class="eyebrow">Older → later</p><h2>${esc(l.name)} tree</h2><p class="tree-help">Select a card for its places, work and evidence. Cards show couples or households; identity hypotheses are labeled between them.</p><ol class="line-tree">${tree}</ol><p class="tree-footnote">${esc(l.limit)}</p></aside><section class="generations" id="generations"><h2>Places and work by generation</h2><p class="generation-intro">Dated clues come from the linked records or attributed accounts. An unfilled job or origin is still unknown.</p>${people}</section></div><section class="branch-timeline" id="branch-timeline"><p class="eyebrow">Dates within this line</p><h2>${esc(l.name)} timeline</h2><ol>${events}</ol><p class="timeline-note">This is a selected record trail, not a complete list of life events. The linked research preserves exact dates, conflicting readings and fuller sources.</p></section><section class="related-lines" id="related-lines"><h2>Continue into a related line</h2><div>${related.map(other=>`<a href="${other.id}.html"><strong>${esc(other.name)}</strong><span>${esc(other.origin)}</span></a>`).join('')}</div></section><section class="line-records" id="branch-records"><h2>Detailed research and originals</h2><ul>${l.articles.map(article=>`<li><a href="${href(article,prefix)}">${esc(article.split('/').at(-1).replace('.md','').replaceAll('-',' '))} ↗</a></li>`).join('')}${l.extras.map(([label,source])=>`<li><a href="${href(source,prefix)}">${esc(label)} ↗</a></li>`).join('')}</ul><p class="line-limit"><strong>Remaining gap:</strong> ${esc(l.limit)}</p></section></main>`;
    await writeFile(path.join(output, pageUrl(l)), shell(`The ${l.name} line`, `${l.origin}. A small family tree, generation-by-generation places and work, and a source-linked timeline.`, body, prefix));
    searchIndex.push({title:`The ${l.name} line`,url:pageUrl(l),category:'branches',text:[l.name,l.aliases,l.origin,l.connection,l.limit,...l.generations.flatMap(g=>[g.names,g.era,g.place,g.work,g.note,g.resources]),...l.events.flatMap(e=>[e.date,e.title,e.text])].join(' ')});
  }
  // Small search index for branches absent from the combined canvas, also used by its selector.
  await writeFile(path.join(output,'explore','line-directory.js'), `window.FAMILY_LINES = ${JSON.stringify(lines.map(l=>({name:l.name,aliases:l.aliases,side:sides[l.side],url:`lines/${l.id}.html`,origin:l.origin}))).replaceAll('<','\\u003c')};\n`);
  return lines.length + 1;
}

export function articleBranchLinks(sourcePath, prefix) {
  const matches = lines.filter(l=>l.articles.includes(sourcePath));
  return matches.length ? `<div class="article-branch-links"><p class="eyebrow">Start with the branch view</p>${matches.map(l=>`<a href="${prefix}${pageUrl(l)}">${esc(l.name)} · tree, places &amp; timeline ↗</a>`).join('')}</div>` : '';
}
